baseURL = 'http://MAlejandroR,github.io/staticSite'
languageCode = 'es-ES'
title = 'DWES Vespertino'
theme =['docsy']
_mege='deep'
 

enableEmoji = true

[params]
custom_css=['/css/estilo.css']

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = true
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

